name: ci

on:
  pull_request:

jobs:
  patch:
    strategy:
      fail-fast: false
      matrix:
        flutter-version: [3.24.2, 3.24.1]

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: ☕ Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: 🎯 Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ matrix.flutter-version }}
          cache: true

      - name: 🤖 AVD Cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29

      - name: 🤖 Cache AVD Snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD Snapshot"

      - name: 🧪 Run Patch E2E Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          script: |
            # Create a new release on Android
            flutter build appbundle --release

            # Download bundletool 1.17.1
            curl -L -o bundletool.jar https://github.com/google/bundletool/releases/download/1.17.1/bundletool-all-1.17.1.jar

            # Build a universal APK
            java -jar bundletool.jar build-apks --overwrite --bundle=build/app/outputs/bundle/release/app-release.aab --output=outputs/my_app.apks --mode=universal

            # Install the APK on a device
            java -jar bundletool.jar install-apks --allow-downgrade --apks=outputs/my_app.apks
